footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
#robot_radius: 0.25  # circular footprint
map_type: costmap

obstacle_layer: 
  obstacle_range: 3.0
  raytrace_range: 3.5
  observation_sources: scan
  scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true,inf_is_valid: true}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  
  inflation_radius:     1.25 

static_layer:
  enabled:              true
  map_topic:            /map


virtual_layer:
  enabled:              true
  zone_topics:          [/virtual_costamp_layer/zone]
  obstacle_topics:      [/virtual_costamp_layer/obsctacles]
  one_zone:             true     
  forms:    
     - [0.4, 0.0]
     - [[0.4, 0.0]]
     - [[-0.4, 0.0],[0.0, 0.4]]
     - [[5, 5],[-5, 5],[-5, -5],[5, -5]]