TebLocalPlannerROS:
  odom_topic: odom
  map_frame: /map

  acc_lim_x: 1.0
  max_vel_x: 0.5 #0.85 1.3
  max_vel_x_backwards: 0.2
  max_vel_theta: 2.75
  min_turning_radius: 0.0
  is_footprint_dynamic: false
  footprint_model:
    # type: "polygon"
    # type: "point"
    # type: "line"
    type: "polygon"
    radius: 0.1 # for type "circular"
    line_start: [0.125, 0.0] # for type "line"
    line_end: [-0.125, 0.0] # for type "line"
    vertices: [[0.17, 0.125], [0.17, -0.125], [-0.17, -0.125], [-0.17, 0.125]]

  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.3
  free_goal_vel: false

  dt_ref: 0.3 #0.3
  dt_hysteresis: 0.1
  min_samples: 4 #3
  global_plan_overwrite_orientation: true
  global_plan_viapoint_sep: 0.25 #-0.1
  max_global_plan_lookahead_dist: 2.0 #2.0
  force_reinit_new_goal_dist: 1.0
  feasibility_check_no_poses: 5
  publish_feedback: false
  allow_init_with_backwards_motion: false
  exact_arc_length: false
  shrink_horizon_backup: true
  shrink_horizon_min_duration: 10.0

  min_obstacle_dist: 0.02 #0.18
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.2
  inflation_dist: 0.08
  include_dynamic_obstacles: true #false
  legacy_obstacle_association: false
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_association_cutoff_factor: 5
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5.0

  no_inner_iterations: 5
  no_outer_iterations: 4
  penalty_epsilon: 0.1  #0.1
  weight_acc_lim_x: 1.0
  weight_acc_lim_theta: 1.0
  weight_max_vel_x: 2.0
  weight_max_vel_theta: 2.0 #2.0 10
  weight_kinematics_nh: 1000.0
  weight_kinematics_forward_drive: 1000.0
  weight_kinematics_turning_radius: 1.0 #1.0
  weight_optimaltime: 4 #10  
  weight_obstacle: 50.0
  weight_viapoint: 1.0 #1.0
  weight_inflation: 0.2 #0.2
  weight_adapt_factor: 2.0
  weight_shortest_path: 0.0  #20

  enable_homotopy_class_planning: true
  enable_multithreading: true
  max_number_classes: 3
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 100.0
  selection_viapoint_cost_scale: 1.0
  selection_alternative_time_cost: false #true
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: false
  viapoints_all_candidates: true
  switching_blocking_period: 0.0

  obstacle_proximity_ratio_max_vel: 0.1 # 接近静态障碍物而降低速度时用作上限的最大速度比  0.8
  obstacle_proximity_lower_bound: 0.1 # 到静态障碍物的距离，速度应较低 0.1
  obstacle_proximity_upper_bound: 1.5 # 到静止障碍物的距离，速度应更高 1.5
  weight_velocity_obstacle_ratio: 100.0 # 约束的权重
